### PR TITLE
Improve formatting options for "config" in ldms cluster config

### PR DESCRIPTION
**Pull request by nick-enoent**
#74 
 New configuration method for "config" in ldms cluster configuration

"config" now represents a list of string configuration command attributes and/or dictionaries of
configuration attributes for plugins.

String formatting allows specifying multiple values for a single attribute
For each string or dictionary in the list, maestro will perform a config command call.

e.g.
```
samplers :
  - daemons : 'sampler-daemons'
    plugins :
      - name : aries_mmr_configurable
        interval : 1s
        config : [ 'action=ls', 'action=reset' ]
```
The above sampler plugin configuration will call config command twice for each action attribute

Dictionaries and strings can be used interchangeably in the "config" list entry

e.g.
```
plugins :
  - name : perfevent
    interval : 1s
    config :
      - name : perfevent
        action : add
        metricname : "PERF_COUNT_HW_CPU_CYCLES"
        pid : $PID
        cpu : $CPU_NUM
        type : 0
        id : 0

      - 'name=perfevent action=add metricname="PERF_COUNT_HW_INSTRUCTIONS" pid=$PID cpu=$CPU_NUM type=0 id=1'
```
Examples of other acceptable formats:
```
stores:
  - name : 'csv_meminfo'
    daemons : 'l2-agg'
    container : ldms_data
    schema : meminfo
    plugin :
      name : store_csv_all
      config : [ 'schema=meminfo, schema=vmstat, schema=procstat' ]
```
```
stores:
  - name : 'csv_meminfo'
    daemons : 'l2-agg'
    container : ldms_data
    schema : meminfo
    plugin :
      name : store_sos
      config : [ { path : /home/DATA } ]
```

### CODE REVIEW

**Comment by baallan** [comment]
@nick-enoent can you please include with this patch a .yaml in config/ that works with it and demonstrates all the ways you expect it to work?

**Comment by tom95858** [comment]
@nick-enoent what about a syntax like this:

config : { "<name>" : [ { dictionary }, "str", {dictionary}, "etc..." ], "<name>" : ...}

But basically you can mix dictionaries and strings. The config value is always an array, but it can combine both raw configuration strings and dictionaries that create these configuration strings.

In any event, each entry in the array is a separate call to the config() method for the plugin.

Currently the "name" must match the plugin name, but when we add multiple configurations for each plugin this will become important.

**Comment by tom95858** [comment]
Ok, markdown ate my syntax again, the "" is the name of the plugin...

**Comment by nick-enoent** [comment]
> @nick-enoent what about a syntax like this:
> 
> config : { "" : [ { dictionary }, "str", {dictionary}, "etc..." ], "" : ...}
> 
> But basically you can mix dictionaries and strings. The config value is always an array, but it can combine both raw configuration strings and dictionaries that create these configuration strings.
> 
> In any event, each entry in the array is a separate call to the config() method for the plugin.
> 
> Currently the "name" must match the plugin name, but when we add multiple configurations for each plugin this will become important.

Sure, I'll remove the config_str option and switch the formatting to support this.

@baallan I'll add an example yaml file once I've finished converting the format of config to support lists of dictionaries and strings

**Comment by baallan** [comment]
@nick-enoent I will be taking a stab at testing this 7/27. It may take a bit as I'll need to coordinate with Schwaller also.

**Comment by nick-enoent** [comment]
Updates to this PR were to resolve merge conflicts #87 and #88 accepted today

**Comment by baallan** [comment]
@nick-enoent To my surprise, etcd3 is still not currently provided by rhel8 or toss4; this makes it difficult to deploy in production. I'm checking with the toss developers to see if we can get it included. if not, we need to think about reopening the noetcd pull request.

**Comment by tom95858** [comment]
@baallan We've been running etcd on RHEL since 7. Can you be more specific about it not being available?  I'm running it now. I'm a bit lost.

**Comment by baallan** [comment]
@tom95858 where did you get it from to install it?
etcd3 is missing from rhel8, rhel9 repositories (and hence missing from toss). There was briefly an old pre-3 version in rhel7. 
The only current rhel-distantly-related packaged version i have found recently is from the centos extras (not to be confused with epel). We need an ibm/redhat supported packaging to get etcd3 included easily in toss4.

pip install is not considered a supported method afaict for TOSS deployments. :(

**Comment by tom95858** [comment]
So kubernetes is not supported on RHEL8? It relies on etcd.

**Comment by baallan** [comment]
@nick-enoent testing as follows generates the stack as seen (required paths anonymized). We need to the v4_config path to work.

```
 maestro_ctrl --ldms_config config/example_config.yaml --prefix foo --generate-config-path dump --debug
Error generating sampler configuration: list indices must be integers or slices, not str 706
Traceback (most recent call last):
  File ".../inst/bin/maestro_ctrl", line 706, in config_v4
    self.write_samplers(fd, group_name)
  File ".../inst/bin/maestro_ctrl", line 600, in write_samplers
    cfg_args[attr] = sampler['config'][attr]
TypeError: list indices must be integers or slices, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../inst/bin/maestro_ctrl", line 781, in <module>
    cluster.config_v4(args.generate_config_path)
  File ".../inst/bin/maestro_ctrl", line 714, in config_v4
    raise ValueError
ValueError
```

**Comment by nick-enoent** [comment]
> @nick-enoent testing as follows generates the stack as seen (required paths anonymized). We need to the v4_config path to work.
> 
> ```
> 
> sha b92ed49
>  maestro_ctrl --ldms_config config/example_config.yaml --prefix foo --generate-config-path dump --debug
> Error generating sampler configuration: list indices must be integers or slices, not str 706
> Traceback (most recent call last):
>   File ".../inst/bin/maestro_ctrl", line 706, in config_v4
>     self.write_samplers(fd, group_name)
>   File ".../inst/bin/maestro_ctrl", line 600, in write_samplers
>     cfg_args[attr] = sampler['config'][attr]
> TypeError: list indices must be integers or slices, not str
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File ".../inst/bin/maestro_ctrl", line 781, in <module>
>     cluster.config_v4(args.generate_config_path)
>   File ".../inst/bin/maestro_ctrl", line 714, in config_v4
>     raise ValueError
> ValueError
> ```

Whoops, thanks for catching this @baallan. I forgot to add support for this format to the configuration generation.

**Comment by baallan** [comment]
> 
> Whoops, thanks for catching this @baallan. I forgot to add support for this format to the configuration generation.

Thanks for the update. I will see about getting it tested again this week. (was out last week mostly).

**Pull request merged**
