### PR TITLE
Support number in expand names

### PR DESCRIPTION
**Pull request by narategithub**

### CODE REVIEW

**Comment by narategithub** [comment]
@nick-enoent Because `expand_hostlist()` expects `str`, if the user give:
```
port: 411
```
`maestro_ctrl` will fail because `411` is an int.

This patch wraps the parameter feeding to `expand_hostlist()`, converting it to `str` if it was a number (float or int).

This is an alternative to #54.

**Comment by narategithub** [comment]
@nick-enoent shall we merge this one too?

**Comment by nick-enoent** [comment]
@narategithub Yes, but we'll need to rebase it on top of the refactor

**Comment by narategithub** [comment]
done :)

**Pull request merged**
