### PR TITLE
project structure refactor

### PR DESCRIPTION
**Pull request by narategithub**
- add `setup.py`
- add `setup.cfg`
- relocate `maetro` and `maestro_ctrl` into `scripts/`
- relocate `*.py` files into `src/maestro/`
- Update `README.md` file to have Installation instruction

### CODE REVIEW

**Comment by narategithub** [comment]
If we're comfortable, we can also make this available on https://pypi.org

**Comment by nick-enoent** [comment]
@narategithub Thanks for doing this, it looks good. I was hoping to do some full testing with it on orion tomorrow before merging. I think there's already a "maestro" project on pypi, so we may need to modify the name strictly for installing via pypi if we decide to make it available. Maybe ovis-maestro?

**Comment by narategithub** [comment]
> @narategithub Thanks for doing this, it looks good. I was hoping to do some full testing with it on orion tomorrow before merging. I think there's already a "maestro" project on pypi, so we may need to modify the name strictly for installing via pypi if we decide to make it available. Maybe ovis-maestro?

`ovis-maestro` sounds good. I just found that out too 😅. Let me change it tonight, and we can decide in the meeting tomorrow.

**Comment by narategithub** [comment]
The PIP name is changed to `ovis-maestro` since https://pypi.org/project/maestro/ is already taken. 

Our python package name and the script name (`maestro`) also conflict with the other maestro (https://pypi.org/project/maestro/). However, I am inclined to keep our script name and our python package name the same (`maestro`) as it is very unlikely that `ovis-maestro` and `maestro` will be in stalled in the same system.

**Review by nick-enoent — APPROVED** [review]

**Comment by nick-enoent** [comment]
@narategithub I merged a minor fix in #49, and it caused a merge conflict in this PR. Do you want to merge #55 before this to avoid having the same issue? As #58 is currently the de facto top of tree running on our systems, I was thinking of tagging it and making it the initial release.

**Comment by narategithub** [comment]
Let's merge 55. I'll resolve the conflict after #55 is merged.

**Comment by narategithub** [comment]
@nick-enoent merged.

**Pull request merged**
