### PR TITLE
Improved yaml parsing

### PR DESCRIPTION
**Pull request by nick-enoent**
Consolidate redundant functions and improve yaml parsing

### CODE REVIEW

**Comment by baallan** [comment]
@nick-enoent the import
from Communicator import cvt_intrvl_str_to_us
breaks maestro_ctrl when it doesn't have access to the ldmsd (optional) python bindings. Please move the function into a supporting file that both drivers (maestro, maestro_ctrl) can load (maestro_util?). 

Traceback (most recent call last):
  File "./maestro_ctrl", line 12, in <module>
    from Communicator import cvt_intrvl_str_to_us
  File "/home/baallan/hpc_home/stria/maestro/Communicator.py", line 49, in <module>
    from ovis_ldms import ldms

**Comment by baallan** [comment]
@nick-enoent  write_updaters assumes interval (or intends to accept None as workable value to be defaulted later) but cvt_intrvl_str_to_us does not handle None gracefully. parsing orion.yaml fails.

**Comment by baallan** [comment]
The handling in cvt of type(int) should be 
return str(interval_s) (a string value) rather than an the int (since the function is documented and used as returning a string).

**Comment by tom95858** [comment]
@nick-enoent can you fix this pull request to resolve the conflicts.

**Pull request closed without merging**
